const translations = {
  en: {
    palm: "Palm",
    buy: "Buy",
    sell_title: "Sell your logs here!",
    sell_btn: "Sell",
    money: "Money",
    logs: "Logs",
    energy: "Energy",
    settings: "Settings",
    appearance_title: "Appearance",
    appearance_mode_title: "Mode",
    appearance_mode_dark: "Sunburned Palm",
    appearance_mode_light: "Light Palm",
    appearance_font_title: "Font",
    languages_title: "Languages",
    likely: "After selling your logs you'll get: ",
    tier: "Tier",
    sham_title: "Ancient Shaman Spell",
    palm_title: "Upgrade Palm",
    sun_title: "Upgrade Sun",
    energy_title: "Improve Stamina",
    boots_title: "Winged Boots",
    tab_normal: "Normal",
    tab_rebirth: "Rebirth",
    tab_work: "Work",
    reb_logs: "Rebirthed Logs",
    rebirth_title: "Rebirth here!",
    rebirth_btn: "Rebirth",
    before_rebirth: "Before you rebith you should:",
    earn: "Earn",
    bussiness_reb: "Run a company",
    workers_reb: "Hire document",
    upgrade_company_reb: "Upgrade Wood Extraction",
    worker_w: "Worker",
    unemployed: "Unemployed",
    working: "Working",
    lvl: "lvl",
    configure: "Configure",
    close: "Close",
    upgrade: "Upgrade",
    worker_config: "Worker Configuration",
    palm_config: "Palm Configuration",
    palm_full: "Palm is full!"
  },

  ru: {
    palm: "Пальма",
    buy: "Купить",
    sell_title: "Продай свои брёвна здесь!",
    sell_btn: "Продать",
    money: "Деньги",
    logs: "Брёвна",
    energy: "Энергия",
    settings: "Настройки",
    appearance_title: "Внешний вид",
    appearance_mode_title: "Режим",
    appearance_mode_dark: "Загорелая пальма",
    appearance_mode_light: "Светлая пальма",
    appearance_font_title: "Шрифт",
    languages_title: "Языки",
    likely: "После продажи брёвен ты получишь: ",
    tier: "Уровень",
    sham_title: "Древнее заклинание шамана",
    palm_title: "Улучшить пальму",
    sun_title: "Улучшить солнце",
    energy_title: "Улучшить выносливость",
    boots_title: "Крылатые сапоги",
    tab_normal: "Обычная",
    tab_rebirth: "Перерождение",
    tab_work: "Работа",
    reb_logs: "Брёвна перерождения",
    rebirth_title: "Переродись здесь!",
    rebirth_btn: "Перерождение",
    before_rebirth: "Перед перерождением тебе следует:",
    earn: "Заработать",
    bussiness_reb: "Управлять компанией",
    workers_reb: "Нанять документ",
    upgrade_company_reb: "Улучшить добычу древесины",
    worker_w: "Работник",
    unemployed: "Безработный",
    working: "Работает",
    lvl: "ур.",
    configure: "Настроить",
    close: "Закрыть",
    upgrade: "Улучшить",
    worker_config: "Настройка работника",
    palm_config: "Настройка пальмы",
    palm_full: "Пальма заполнена!"
  },

  ru_old: {
    palm: "Пальма",
    buy: "Купити",
    sell_title: "Продати древеса зде!",
    sell_btn: "Продати",
    money: "Сребро",
    logs: "Древа",
    energy: "Сила",
    settings: "Устроение",
    appearance_title: "Образ",
    appearance_mode_title: "Лик",
    appearance_mode_dark: "Пальма зноя",
    appearance_mode_light: "Пальма светла",
    appearance_font_title: "Писмо",
    languages_title: "Языцы",
    likely: "По продаже древъ приимеши: ",
    tier: "Степень",
    sham_title: "Волхвское древнее заклятие",
    palm_title: "Возвысити пальму",
    sun_title: "Возвысити солнце",
    energy_title: "Укрепити силу",
    boots_title: "Крилатии сапози",
    tab_normal: "Обычныи",
    tab_rebirth: "Возрождение",
    tab_work: "Труд",
    reb_logs: "Древа возрождениа",
    rebirth_title: "Возродися зде!",
    rebirth_btn: "Возрождение",
    before_rebirth: "Прежде возрождениа подобает:",
    earn: "Стяжати",
    bussiness_reb: "Владати дружиною",
    workers_reb: "Няти грамоту",
    upgrade_company_reb: "Возвысити добывание древъ",
    worker_w: "Трудник",
    unemployed: "Без труда",
    working: "Труждается",
    lvl: "ступ.",
    configure: "Устроити",
    close: "Затворити",
    upgrade: "Возвысити",
    worker_config: "Устроение трудника",
    palm_config: "Устроение пальмы",
    palm_full: "Пальма исполнена!"
  },

  pl: {
    palm: "Palma",
    buy: "Kup",
    sell_title: "Sprzedaj swoje drewno tutaj!",
    sell_btn: "Sprzedaj",
    money: "Pieniądze",
    logs: "Drewno",
    energy: "Energia",
    settings: "Ustawienia",
    appearance_title: "Wygląd",
    appearance_mode_title: "Tryb",
    appearance_mode_dark: "Opalona Palma",
    appearance_mode_light: "Jasna Palma",
    appearance_font_title: "Czcionka",
    languages_title: "Języki",
    likely: "Po sprzedaży drewna otrzymasz: ",
    tier: "Poziom",
    sham_title: "Starożytne Zaklęcie Szamana",
    palm_title: "Ulepsz Palmę",
    sun_title: "Ulepsz Słońce",
    energy_title: "Popraw Wytrzymałość",
    boots_title: "Skrzydlate Buty",
    tab_normal: "Normalny",
    tab_rebirth: "Odrodzenie",
    tab_work: "Praca",
    reb_logs: "Drewno Odrodzenia",
    rebirth_title: "Odrodź się tutaj!",
    rebirth_btn: "Odrodzenie",
    before_rebirth: "Zanim się odrodzisz powinieneś:",
    earn: "Zarób",
    bussiness_reb: "Prowadź firmę",
    workers_reb: "Zatrudnij dokument",
    upgrade_company_reb: "Ulepsz Wydobycie Drewna",
    worker_w: "Pracownik",
    unemployed: "Bezrobotny",
    working: "Pracuje",
    lvl: "poziom",
    configure: "Skonfiguruj",
    close: "Zamknij",
    upgrade: "Ulepsz",
    worker_config: "Konfiguracja Pracownika",
    palm_config: "Konfiguracja Palmy",
    palm_full: "Palma jest pełna!"
  },
  
  sr: {
    palm: "Palma",
    buy: "Kupi",
    sell_title: "Продај своја дрва овде!",
    sell_btn: "Продај",
    money: "Новац",
    logs: "Дрва",
    energy: "Енергија",
    settings: "Подешавања",
    appearance_title: "Изглед",
    appearance_mode_title: "Режим",
    appearance_mode_dark: "Опаљена палма",
    appearance_mode_light: "Светла палма",
    appearance_font_title: "Фонт",
    languages_title: "Језици",
    likely: "Након продаје дрва добићеш: ",
    tier: "Ниво",
    sham_title: "Древна шаманска чаролија",
    palm_title: "Унапреди палму",
    sun_title: "Унапреди сунце",
    energy_title: "Побољшај издржљивост",
    boots_title: "Крилате чизме",
    tab_normal: "Нормално",
    tab_rebirth: "Поново рођење",
    tab_work: "Рад",
    reb_logs: "Поново рођена дрва",
    rebirth_title: "Поново се роди овде!",
    rebirth_btn: "Поново рођење",
    before_rebirth: "Пре него што се поново родиш треба да:",
    earn: "Заради",
    bussiness_reb: "Води компанију",
    workers_reb: "Запосли документ",
    upgrade_company_reb: "Унапреди вађење дрвета",
    worker_w: "Радник",
    unemployed: "Незапослен",
    working: "Ради",
    lvl: "ниво",
    configure: "Подеси",
    close: "Затвори",
    upgrade: "Унапреди",
    worker_config: "Подешавање радника",
    palm_config: "Подешавање палме",
    palm_full: "Палма је пуна!"
  },

  fr: {
    palm: "Palmier",
    buy: "Acheter",
    sell_title: "Vendez vos bûches ici !",
    sell_btn: "Vendre",
    money: "Argent",
    logs: "Bûches",
    energy: "Énergie",
    settings: "Paramètres",
    appearance_title: "Apparence",
    appearance_mode_title: "Mode",
    appearance_mode_dark: "Palmier Bronzé",
    appearance_mode_light: "Palmier Clair",
    appearance_font_title: "Police",
    languages_title: "Langues",
    likely: "Après la vente, vous recevrez : ",
    tier: "Niveau",
    sham_title: "Sort ancien du chaman",
    palm_title: "Améliorer le palmier",
    sun_title: "Améliorer le soleil",
    energy_title: "Améliorer l'endurance",
    boots_title: "Bottes ailées",
    tab_normal: "Normal",
    tab_rebirth: "Renaissance",
    tab_work: "Travail",
    reb_logs: "Bûches de Renaissance",
    rebirth_title: "Re-naissez ici !",
    rebirth_btn: "Renaissance",
    before_rebirth: "Avant de renaître vous devriez :",
    earn: "Gagner",
    bussiness_reb: "Diriger une entreprise",
    workers_reb: "Embaucher un document",
    upgrade_company_reb: "Améliorer l'Extraction du Bois",
    worker_w: "Ouvrier",
    unemployed: "Sans emploi",
    working: "Au travail",
    lvl: "niv.",
    configure: "Configurer",
    close: "Fermer",
    upgrade: "Améliorer",
    worker_config: "Configuration de l'Ouvrier",
    palm_config: "Configuration du Palmier",
    palm_full: "Le palmier est plein !"
  },

  cu: {
    palm: "Пальма",
    buy: "Кѹпити",
    sell_title: "Продай древеса зде!",
    sell_btn: "Продати",
    money: "Сребро",
    logs: "Древеса",
    energy: "Сила",
    settings: "Устав",
    appearance_title: "Вид",
    appearance_mode_title: "Образ",
    appearance_mode_dark: "Пальма зноя",
    appearance_mode_light: "Пальма светла",
    appearance_font_title: "Писание",
    languages_title: "Языцы",
    likely: "По продаже древъ приимеши: ",
    tier: "Степень",
    sham_title: "Древнее волхвование",
    palm_title: "Возвысити пальму",
    sun_title: "Возвысити солнце",
    energy_title: "Укрепити силу",
    boots_title: "Крилатии сапоги",
    tab_normal: "Обычьныи",
    tab_rebirth: "Возрождение",
    tab_work: "Дѣло",
    reb_logs: "Древа возрожденїа",
    rebirth_title: "Возроди сѧ зде!",
    rebirth_btn: "Возрождение",
    before_rebirth: "Прѣжде возрожденїа подобаетъ:",
    earn: "Стѧжати",
    bussiness_reb: "Владати дружиною",
    workers_reb: "Нѧти грамотѫ",
    upgrade_company_reb: "Возвысити добыванїе древъ",
    worker_w: "Дѣлатель",
    unemployed: "Безъ дѣла",
    working: "Трѹждаетъ сѧ",
    lvl: "стѫпен.",
    configure: "Устроити",
    close: "Затворити",
    upgrade: "Возвысити",
    worker_config: "Устроенїе дѣлателя",
    palm_config: "Устроенїе пальмы",
    palm_full: "Пальма исплънена!"
  },

  el: {
    palm: "Φοινικιά",
    buy: "Αγορά",
    sell_title: "Πούλησε τα ξύλα σου εδώ!",
    sell_btn: "Πώληση",
    money: "Χρήματα",
    logs: "Ξύλα",
    energy: "Ενέργεια",
    settings: "Ρυθμίσεις",
    appearance_title: "Εμφάνιση",
    appearance_mode_title: "Λειτουργία",
    appearance_mode_dark: "Ηλιοκαμένη Φοινικιά",
    appearance_mode_light: "Φωτεινή Φοινικιά",
    appearance_font_title: "Γραμματοσειρά",
    languages_title: "Γλώσσες",
    likely: "Μετά την πώληση θα λάβεις: ",
    tier: "Βαθμίδα",
    sham_title: "Αρχαίο Ξόρκι Σαμάνου",
    palm_title: "Αναβάθμιση Φοινικιάς",
    sun_title: "Αναβάθμιση Ήλιου",
    energy_title: "Βελτίωση Αντοχής",
    boots_title: "Φτερωτές Μπότες",
    tab_normal: "Κανονικό",
    tab_rebirth: "Αναγέννηση",
    tab_work: "Δουλειά",
    reb_logs: "Ξύλα Αναγέννησης",
    rebirth_title: "Αναγεννήσου εδώ!",
    rebirth_btn: "Αναγέννηση",
    before_rebirth: "Πριν αναγεννηθείς πρέπει να:",
    earn: "Κέρδισε",
    bussiness_reb: "Διεύθυνε εταιρεία",
    workers_reb: "Πρόσλαβε έγγραφο",
    upgrade_company_reb: "Αναβάθμιση Εξόρυξης Ξύλου",
    worker_w: "Εργάτης",
    unemployed: "Άνεργος",
    working: "Δουλεύει",
    lvl: "επίπ.",
    configure: "Διαμόρφωση",
    close: "Κλείσιμο",
    upgrade: "Αναβάθμιση",
    worker_config: "Διαμόρφωση Εργάτη",
    palm_config: "Διαμόρφωση Φοινικιάς",
    palm_full: "Η φοινικιά είναι γεμάτη!"
  },

  ar: {
    palm: "نخلة",
    buy: "اشتر",
    sell_title: "بع أخشابك هنا!",
    sell_btn: "بيع",
    money: "المال",
    logs: "الأخشاب",
    energy: "الطاقة",
    settings: "الإعدادات",
    appearance_title: "المظهر",
    appearance_mode_title: "الوضع",
    appearance_mode_dark: "نخلة محترقة بالشمس",
    appearance_mode_light: "نخلة مضيئة",
    appearance_font_title: "الخط",
    languages_title: "اللغات",
    likely: "بعد البيع ستحصل على: ",
    tier: "المستوى",
    sham_title: "تعويذة الشامان القديمة",
    palm_title: "تطوير النخلة",
    sun_title: "تطوير الشمس",
    energy_title: "تحسين التحمل",
    boots_title: "أحذية مجنحة",
    tab_normal: "عادي",
    tab_rebirth: "ولادة جديدة",
    tab_work: "عمل",
    reb_logs: "أخشاب الولادة الجديدة",
    rebirth_title: "تولد من جديد هنا!",
    rebirth_btn: "ولادة جديدة",
    before_rebirth: "قبل أن تولد من جديد يجب أن:",
    earn: "اكسب",
    bussiness_reb: "إدارة شركة",
    workers_reb: "توظيف وثيقة",
    upgrade_company_reb: "ترقية استخراج الخشب",
    worker_w: "عامل",
    unemployed: "عاطل",
    working: "يعمل",
    lvl: "مستوى",
    configure: "تكوين",
    close: "إغلاق",
    upgrade: "ترقية",
    worker_config: "تكوين العامل",
    palm_config: "تكوين النخلة",
    palm_full: "النخلة ممتلئة!"
  },

  de: {
    palm: "Palme",
    buy: "Kaufen",
    sell_title: "Verkaufe deine Holzstämme hier!",
    sell_btn: "Verkaufen",
    money: "Geld",
    logs: "Holz",
    energy: "Energie",
    settings: "Einstellungen",
    appearance_title: "Aussehen",
    appearance_mode_title: "Modus",
    appearance_mode_dark: "Sonnengebrannte Palme",
    appearance_mode_light: "Helle Palme",
    appearance_font_title: "Schriftart",
    languages_title: "Sprachen",
    likely: "Nach dem Verkauf erhältst du: ",
    tier: "Stufe",
    sham_title: "Uralter Schamanenzauber",
    palm_title: "Palme verbessern",
    sun_title: "Sonne verbessern",
    energy_title: "Ausdauer verbessern",
    boots_title: "Geflügelte Stiefel",
    tab_normal: "Normal",
    tab_rebirth: "Wiedergeburt",
    tab_work: "Arbeit",
    reb_logs: "Wiedergeburt Holz",
    rebirth_title: "Werde hier wiedergeboren!",
    rebirth_btn: "Wiedergeburt",
    before_rebirth: "Bevor du wiedergeboren wirst solltest du:",
    earn: "Verdiene",
    bussiness_reb: "Führe ein Unternehmen",
    workers_reb: "Stelle ein Dokument ein",
    upgrade_company_reb: "Holzgewinnung verbessern",
    worker_w: "Arbeiter",
    unemployed: "Arbeitslos",
    working: "Arbeitet",
    lvl: "St.",
    configure: "Konfigurieren",
    close: "Schließen",
    upgrade: "Verbessern",
    worker_config: "Arbeiterkonfiguration",
    palm_config: "Palmenkonfiguration",
    palm_full: "Palme ist voll!"
  },

  zh: {
    palm: "棕榈树",
    buy: "购买",
    sell_title: "在这里出售你的木材！",
    sell_btn: "出售",
    money: "金钱",
    logs: "木材",
    energy: "能量",
    settings: "设置",
    appearance_title: "外观",
    appearance_mode_title: "模式",
    appearance_mode_dark: "晒黑的棕榈",
    appearance_mode_light: "明亮的棕榈",
    appearance_font_title: "字体",
    languages_title: "语言",
    likely: "出售后你将获得：",
    tier: "等级",
    sham_title: "远古萨满法术",
    palm_title: "升级棕榈",
    sun_title: "升级太阳",
    energy_title: "提升耐力",
    boots_title: "翼靴",
    tab_normal: "普通",
    tab_rebirth: "重生",
    tab_work: "工作",
    reb_logs: "重生木材",
    rebirth_title: "在这里重生！",
    rebirth_btn: "重生",
    before_rebirth: "重生前你应该：",
    earn: "赚取",
    bussiness_reb: "经营公司",
    workers_reb: "雇佣文件",
    upgrade_company_reb: "升级木材提取",
    worker_w: "工人",
    unemployed: "失业",
    working: "工作中",
    lvl: "等级",
    configure: "配置",
    close: "关闭",
    upgrade: "升级",
    worker_config: "工人配置",
    palm_config: "棕榈配置",
    palm_full: "棕榈树已满！"
  },

  ja: {
    palm: "ヤシの木",
    buy: "購入",
    sell_title: "ここで木材を売ろう！",
    sell_btn: "売る",
    money: "お金",
    logs: "木材",
    energy: "エネルギー",
    settings: "設定",
    appearance_title: "外観",
    appearance_mode_title: "モード",
    appearance_mode_dark: "日焼けしたヤシ",
    appearance_mode_light: "明るいヤシ",
    appearance_font_title: "フォント",
    languages_title: "言語",
    likely: "売却後に得られるもの：",
    tier: "ランク",
    sham_title: "古代シャーマンの呪文",
    palm_title: "ヤシを強化",
    sun_title: "太陽を強化",
    energy_title: "スタミナ向上",
    boots_title: "翼のブーツ",
    tab_normal: "通常",
    tab_rebirth: "転生",
    tab_work: "仕事",
    reb_logs: "転生木材",
    rebirth_title: "ここで転生しよう！",
    rebirth_btn: "転生",
    before_rebirth: "転生する前に：",
    earn: "稼ぐ",
    bussiness_reb: "会社を経営",
    workers_reb: "書類を雇用",
    upgrade_company_reb: "木材採取を強化",
    worker_w: "労働者",
    unemployed: "無職",
    working: "働いている",
    lvl: "レベル",
    configure: "設定",
    close: "閉じる",
    upgrade: "強化",
    worker_config: "労働者設定",
    palm_config: "ヤシの木設定",
    palm_full: "ヤシの木がいっぱいです！"
  },

  am: {
    palm: "ዘንባባ",
    buy: "ግዛ",
    sell_title: "እንጨቶችህን እዚህ ሽጥ!",
    sell_btn: "ሽጥ",
    money: "ገንዘብ",
    logs: "እንጨት",
    energy: "ኃይል",
    settings: "ቅንብሮች",
    appearance_title: "መልክ",
    appearance_mode_title: "ሁኔታ",
    appearance_mode_dark: "በፀሐይ የተቃጠለ ዘንባባ",
    appearance_mode_light: "ብሩህ ዘንባባ",
    appearance_font_title: "ፊደል",
    languages_title: "ቋንቋዎች",
    likely: "ከሽያጭ በኋላ ትቀበላለህ: ",
    tier: "ደረጃ",
    sham_title: "ጥንታዊ የሻማን ስልት",
    palm_title: "ዘንባባ ማሻሻል",
    sun_title: "ፀሐይ ማሻሻል",
    energy_title: "ኃይል ማሻሻል",
    boots_title: "ክንፍ ያላቸው ጫማዎች",
    tab_normal: "መደበኛ",
    tab_rebirth: "እንደገና ልደት",
    tab_work: "ስራ",
    reb_logs: "የተደገመ እንጨት",
    rebirth_title: "እዚህ እንደገና ተወለድ!",
    rebirth_btn: "እንደገና ልደት",
    before_rebirth: "ከመደገምዎ በፊት ማድረግ ያለብዎት:",
    earn: "ተጠቅም",
    bussiness_reb: "ኩባንያ አስተዳድር",
    workers_reb: "ወረቀት ቅጠር",
    upgrade_company_reb: "የእንጨት ማውጣት አሻሽል",
    worker_w: "ሠራተኛ",
    unemployed: "ሥራ አልባ",
    working: "በሥራ ላይ",
    lvl: "ደረጃ",
    configure: "ግብአት",
    close: "ዝጋ",
    upgrade: "አሻሽል",
    worker_config: "የሠራተኛ ግብአት",
    palm_config: "የዘንባባ ግብአት",
    palm_full: "ዘንባባው እስከ ጫፍ ሞልቷል!"
  },

  hi: {
    palm: "पाम",
    buy: "खरीदें",
    sell_title: "अपनी लकड़ी यहाँ बेचें!",
    sell_btn: "बेचें",
    money: "पैसा",
    logs: "लकड़ी",
    energy: "ऊर्जा",
    settings: "सेटिंग्स",
    appearance_title: "दिखावट",
    appearance_mode_title: "मोड",
    appearance_mode_dark: "सनबर्न पाम",
    appearance_mode_light: "लाइट पाम",
    appearance_font_title: "फ़ॉन्ट",
    languages_title: "भाषाएँ",
    likely: "बेचने के बाद आपको मिलेगा: ",
    tier: "स्तर",
    sham_title: "प्राचीन शमन मंत्र",
    palm_title: "पाम अपग्रेड करें",
    sun_title: "सूरज अपग्रेड करें",
    energy_title: "स्टैमिना सुधारें",
    boots_title: "पंख वाले बूट",
    tab_normal: "सामान्य",
    tab_rebirth: "पुनर्जन्म",
    tab_work: "काम",
    reb_logs: "पुनर्जन्म लकड़ी",
    rebirth_title: "यहाँ पुनर्जन्म लें!",
    rebirth_btn: "पुनर्जन्म",
    before_rebirth: "पुनर्जन्म लेने से पहले आपको:",
    earn: "कमाएँ",
    bussiness_reb: "कंपनी चलाएँ",
    workers_reb: "दस्तावेज़ किराए पर लें",
    upgrade_company_reb: "लकड़ी निष्कर्षण अपग्रेड",
    worker_w: "कर्मचारी",
    unemployed: "बेरोजगार",
    working: "काम कर रहे",
    lvl: "स्तर",
    configure: "कॉन्फ़िगर करें",
    close: "बंद करें",
    upgrade: "अपग्रेड",
    worker_config: "कर्मचारी कॉन्फ़िगरेशन",
    palm_config: "पाम कॉन्फ़िगरेशन",
    palm_full: "पाम भरा हुआ है!"
  },

  it: {
    palm: "Palma",
    buy: "Compra",
    sell_title: "Vendi i tuoi tronchi qui!",
    sell_btn: "Vendi",
    money: "Soldi",
    logs: "Tronchi",
    energy: "Energia",
    settings: "Impostazioni",
    appearance_title: "Aspetto",
    appearance_mode_title: "Modalità",
    appearance_mode_dark: "Palma Abbronzata",
    appearance_mode_light: "Palma Chiara",
    appearance_font_title: "Font",
    languages_title: "Lingue",
    likely: "Dopo la vendita otterrai: ",
    tier: "Livello",
    sham_title: "Antico Incantesimo dello Sciamano",
    palm_title: "Migliora Palma",
    sun_title: "Migliora Sole",
    energy_title: "Migliora Resistenza",
    boots_title: "Stivali Alati",
    tab_normal: "Normale",
    tab_rebirth: "Rinascita",
    tab_work: "Lavoro",
    reb_logs: "Tronchi di Rinascita",
    rebirth_title: "Rinasci qui!",
    rebirth_btn: "Rinascita",
    before_rebirth: "Prima di rinascere dovresti:",
    earn: "Guadagna",
    bussiness_reb: "Gestisci un'azienda",
    workers_reb: "Assumi documento",
    upgrade_company_reb: "Migliora Estrazione Legno",
    worker_w: "Lavoratore",
    unemployed: "Disoccupato",
    working: "Al lavoro",
    lvl: "liv.",
    configure: "Configura",
    close: "Chiudi",
    upgrade: "Migliora",
    worker_config: "Configurazione Lavoratore",
    palm_config: "Configurazione Palma",
    palm_full: "La palma è piena!"
  },

  fi: {
    palm: "Palmu",
    buy: "Osta",
    sell_title: "Myy puusi täällä!",
    sell_btn: "Myy",
    money: "Raha",
    logs: "Puut",
    energy: "Energia",
    settings: "Asetukset",
    appearance_title: "Ulkoasu",
    appearance_mode_title: "Tila",
    appearance_mode_dark: "Auringon Polttama Palmu",
    appearance_mode_light: "Vaalea Palmu",
    appearance_font_title: "Fontti",
    languages_title: "Kielet",
    likely: "Myynnin jälkeen saat: ",
    tier: "Taso",
    sham_title: "Muinaisen Shamaanin Loitsu",
    palm_title: "Päivitä Palmu",
    sun_title: "Päivitä Aurinko",
    energy_title: "Paranna Kestävyyttä",
    boots_title: "Siivekkäät Saappaat",
    tab_normal: "Normaali",
    tab_rebirth: "Uudelleensyntyminen",
    tab_work: "Työ",
    reb_logs: "Uudelleensyntyneet Puut",
    rebirth_title: "Synny uudelleen täällä!",
    rebirth_btn: "Uudelleensyntyminen",
    before_rebirth: "Ennen uudelleensyntymistä sinun tulisi:",
    earn: "Ansaitse",
    bussiness_reb: "Johda yritystä",
    workers_reb: "Palkkaa asiakirja",
    upgrade_company_reb: "Päivitä Puunpoisto",
    worker_w: "Työntekijä",
    unemployed: "Työtön",
    working: "Työskentelee",
    lvl: "tas.",
    configure: "Määritä",
    close: "Sulje",
    upgrade: "Päivitä",
    worker_config: "Työntekijän Määritys",
    palm_config: "Palmun Määritys",
    palm_full: "Palmu on täynnä!"
  },

  uk: {
    palm: "Пальма",
    buy: "Купити",
    sell_title: "Продай свої колоди тут!",
    sell_btn: "Продати",
    money: "Гроші",
    logs: "Колоди",
    energy: "Енергія",
    settings: "Налаштування",
    appearance_title: "Зовнішній вигляд",
    appearance_mode_title: "Режим",
    appearance_mode_dark: "Засмагла пальма",
    appearance_mode_light: "Світла пальма",
    appearance_font_title: "Шрифт",
    languages_title: "Мови",
    likely: "Після продажу ти отримаєш: ",
    tier: "Рівень",
    sham_title: "Давнє шаманське закляття",
    palm_title: "Покращити пальму",
    sun_title: "Покращити сонце",
    energy_title: "Покращити витривалість",
    boots_title: "Крилаті чоботи",
    tab_normal: "Звичайний",
    tab_rebirth: "Переродження",
    tab_work: "Робота",
    reb_logs: "Колоди переродження",
    rebirth_title: "Переродись тут!",
    rebirth_btn: "Переродження",
    before_rebirth: "Перед переродженням тобі слід:",
    earn: "Заробити",
    bussiness_reb: "Керувати компанією",
    workers_reb: "Найняти документ",
    upgrade_company_reb: "Покращити видобуток деревини",
    worker_w: "Робітник",
    unemployed: "Безробітний",
    working: "Працює",
    lvl: "рів.",
    configure: "Налаштувати",
    close: "Закрити",
    upgrade: "Покращити",
    worker_config: "Налаштування робітника",
    palm_config: "Налаштування пальми",
    palm_full: "Пальма заповнена!"
  },

  pt: {
    palm: "Palmeira",
    buy: "Comprar",
    sell_title: "Venda suas toras aqui!",
    sell_btn: "Vender",
    money: "Dinheiro",
    logs: "Toras",
    energy: "Energia",
    settings: "Configurações",
    appearance_title: "Aparência",
    appearance_mode_title: "Modo",
    appearance_mode_dark: "Palmeira Queimada pelo Sol",
    appearance_mode_light: "Palmeira Clara",
    appearance_font_title: "Fonte",
    languages_title: "Idiomas",
    likely: "Após a venda você receberá: ",
    tier: "Nível",
    sham_title: "Feitiço Antigo do Xamã",
    palm_title: "Melhorar Palmeira",
    sun_title: "Melhorar Sol",
    energy_title: "Melhorar Resistência",
    boots_title: "Botas Aladas",
    tab_normal: "Normal",
    tab_rebirth: "Renascimento",
    tab_work: "Trabalho",
    reb_logs: "Toras do Renascimento",
    rebirth_title: "Renasça aqui!",
    rebirth_btn: "Renascimento",
    before_rebirth: "Antes de renascer você deve:",
    earn: "Ganhar",
    bussiness_reb: "Gerenciar uma empresa",
    workers_reb: "Contratar documento",
    upgrade_company_reb: "Melhorar Extração de Madeira",
    worker_w: "Trabalhador",
    unemployed: "Desempregado",
    working: "Trabalhando",
    lvl: "nív.",
    configure: "Configurar",
    close: "Fechar",
    upgrade: "Melhorar",
    worker_config: "Configuração do Trabalhador",
    palm_config: "Configuração da Palmeira",
    palm_full: "A palmeira está cheia!"
  },

  es: {
    palm: "Palmera",
    buy: "Comprar",
    sell_title: "¡Vende tus troncos aquí!",
    sell_btn: "Vender",
    money: "Dinero",
    logs: "Troncos",
    energy: "Energía",
    settings: "Configuración",
    appearance_title: "Apariencia",
    appearance_mode_title: "Modo",
    appearance_mode_dark: "Palmera Bronceada",
    appearance_mode_light: "Palmera Clara",
    appearance_font_title: "Fuente",
    languages_title: "Idiomas",
    likely: "Después de vender recibirás: ",
    tier: "Nivel",
    sham_title: "Hechizo Antiguo de Chamán",
    palm_title: "Mejorar Palmera",
    sun_title: "Mejorar Sol",
    energy_title: "Mejorar Resistencia",
    boots_title: "Botas Aladas",
    tab_normal: "Normal",
    tab_rebirth: "Renacimiento",
    tab_work: "Trabajo",
    reb_logs: "Troncos de Renacimiento",
    rebirth_title: "¡Renace aquí!",
    rebirth_btn: "Renacimiento",
    before_rebirth: "Antes de renacer deberías:",
    earn: "Ganar",
    bussiness_reb: "Gestionar una empresa",
    workers_reb: "Contratar documento",
    upgrade_company_reb: "Mejorar Extracción de Madera",
    worker_w: "Trabajador",
    unemployed: "Desempleado",
    working: "Trabajando",
    lvl: "niv.",
    configure: "Configurar",
    close: "Cerrar",
    upgrade: "Mejorar",
    worker_config: "Configuración del Trabajador",
    palm_config: "Configuración de la Palmera",
    palm_full: "¡La palmera está llena!"
  },

  ka: {
    palm: "პალმა",
    buy: "ყიდვა",
    sell_title: "აქ გაყიდე შენი მორები!",
    sell_btn: "გაყიდვა",
    money: "ფული",
    logs: "მორები",
    energy: "ენერგია",
    settings: "პარამეტრები",
    appearance_title: "გარეგნობა",
    appearance_mode_title: "რეჟიმი",
    appearance_mode_dark: "მზით დამწვარი პალმა",
    appearance_mode_light: "ნათელი პალმა",
    appearance_font_title: "შრიფტი",
    languages_title: "ენები",
    likely: "გაყიდვის შემდეგ მიიღებ: ",
    tier: "დონე",
    sham_title: "უძველესი შამანის შელოცვა",
    palm_title: "პალმის გაუმჯობესება",
    sun_title: "მზის გაუმჯობესება",
    energy_title: "გამძლეობის გაუმჯობესება",
    boots_title: "ფრთიანი ჩექმები",
    tab_normal: "ნორმალური",
    tab_rebirth: "დაბადება",
    tab_work: "სამუშაო",
    reb_logs: "დაბადების მორები",
    rebirth_title: "აქ დაიბადე!",
    rebirth_btn: "დაბადება",
    before_rebirth: "დაბადებამდე უნდა:",
    earn: "მიიღე",
    bussiness_reb: "კომპანიის მართვა",
    workers_reb: "დოკუმენტის დაქირავება",
    upgrade_company_reb: "ხის მოპოვების გაუმჯობესება",
    worker_w: "მუშა",
    unemployed: "უმუშევარი",
    working: "მუშაობს",
    lvl: "დონე",
    configure: "კონფიგურაცია",
    close: "დახურვა",
    upgrade: "გაუმჯობესება",
    worker_config: "მუშის კონფიგურაცია",
    palm_config: "პალმის კონფიგურაცია",
    palm_full: "პალმა სავსეა!"
  },

  tr: {
    palm: "Palmiye",
    buy: "Satın Al",
    sell_title: "Kütüklerini burada sat!",
    sell_btn: "Sat",
    money: "Para",
    logs: "Kütükler",
    energy: "Enerji",
    settings: "Ayarlar",
    appearance_title: "Görünüm",
    appearance_mode_title: "Mod",
    appearance_mode_dark: "Güneşte Yanmış Palmiye",
    appearance_mode_light: "Açık Renkli Palmiye",
    appearance_font_title: "Yazı Tipi",
    languages_title: "Diller",
    likely: "Satıştan sonra kazanacağın: ",
    tier: "Seviye",
    sham_title: "Kadim Şaman Büyüsü",
    palm_title: "Palmiyeyi Geliştir",
    sun_title: "Güneşi Geliştir",
    energy_title: "Dayanıklılığı Artır",
    boots_title: "Kanatlı Çizmeler",
    tab_normal: "Normal",
    tab_rebirth: "Yeniden Doğuş",
    tab_work: "İş",
    reb_logs: "Yeniden Doğuş Kütükleri",
    rebirth_title: "Burada Yeniden Doğ!",
    rebirth_btn: "Yeniden Doğuş",
    before_rebirth: "Yeniden doğmadan önce şunları yapmalısın:",
    earn: "Kazan",
    bussiness_reb: "Şirket Yönet",
    workers_reb: "Belge İşe Al",
    upgrade_company_reb: "Ahşap Çıkarmayı Geliştir",
    worker_w: "İşçi",
    unemployed: "İşsiz",
    working: "Çalışıyor",
    lvl: "seviye",
    configure: "Yapılandır",
    close: "Kapat",
    upgrade: "Geliştir",
    worker_config: "İşçi Yapılandırması",
    palm_config: "Palmiye Yapılandırması",
    palm_full: "Palmiye dolu!"
  },

  af: {
    palm: "Palm",
    buy: "Koop",
    sell_title: "Verkoop jou hout hier!",
    sell_btn: "Verkoop",
    money: "Geld",
    logs: "Hout",
    energy: "Energie",
    settings: "Instellings",
    appearance_title: "Voorkoms",
    appearance_mode_title: "Modus",
    appearance_mode_dark: "Sonverbrande Palm",
    appearance_mode_light: "Ligte Palm",
    appearance_font_title: "Lettertipe",
    languages_title: "Tale",
    likely: "Na die verkoop kry jy: ",
    tier: "Vlak",
    sham_title: "Antieke Sjamaan-spreuk",
    palm_title: "Verbeter Palm",
    sun_title: "Verbeter Son",
    energy_title: "Verbeter Uithouvermoë",
    boots_title: "Gevlerkte Stewels",
    tab_normal: "Normaal",
    tab_rebirth: "Wedergeboorte",
    tab_work: "Werk",
    reb_logs: "Wedergebore Hout",
    rebirth_title: "Word hier wedergebore!",
    rebirth_btn: "Wedergeboorte",
    before_rebirth: "Voordat jy wedergebore word moet jy:",
    earn: "Verdien",
    bussiness_reb: "Bestuur 'n Maatskappy",
    workers_reb: "Huur dokument",
    upgrade_company_reb: "Verbeter Houtontginning",
    worker_w: "Werker",
    unemployed: "Werkloos",
    working: "Werk",
    lvl: "vlak",
    configure: "Konfigureer",
    close: "Sluit",
    upgrade: "Verbeter",
    worker_config: "Werkerkonfigurasie",
    palm_config: "Palmkonfigurasie",
    palm_full: "Palm is vol!"
  }
};