const translations = {
  en: {
    sell_title: "Sell your logs here!",
    sell_btn: "Sell",
    money: "Money",
    logs: "Logs",
    energy: "Energy",
    settings: "Settings",
    appearance_title: "Appearance",
    appearance_mode_title: "Mode",
    appearance_mode_dark: "Sunburned Palm",
    appearance_mode_light: "Light Palm",
    appearance_font_title: "Font",
    languages_title: "Languages",
    likely: "After selling your logs you'll get: ",
    tier: "Tier",
    sham_title: "Ancient Shaman Spell",
    palm_title: "Upgrade Palm",
    sun_title: "Upgrade Sun",
    energy_title: "Improve Stamina",
    boots_title: "Winged Boots"
  },

  ru: {
    sell_title: "Продай свои брёвна здесь!",
    sell_btn: "Продать",
    money: "Деньги",
    logs: "Брёвна",
    energy: "Энергия",
    settings: "Настройки",
    appearance_title: "Внешний вид",
    appearance_mode_title: "Режим",
    appearance_mode_dark: "Загорелая пальма",
    appearance_mode_light: "Светлая пальма",
    appearance_font_title: "Шрифт",
    languages_title: "Языки",
    likely: "После продажи брёвен ты получишь: ",
    tier: "Уровень",
    sham_title: "Древнее заклинание шамана",
    palm_title: "Улучшить пальму",
    sun_title: "Улучшить солнце",
    energy_title: "Улучшить выносливость",
    boots_title: "Крылатые сапоги"
  },

  ru_old: {
    sell_title: "Продати древеса зде!",
    sell_btn: "Продати",
    money: "Сребро",
    logs: "Древа",
    energy: "Сила",
    settings: "Устроение",
    appearance_title: "Образ",
    appearance_mode_title: "Лик",
    appearance_mode_dark: "Пальма зноя",
    appearance_mode_light: "Пальма светла",
    appearance_font_title: "Писмо",
    languages_title: "Языцы",
    likely: "По продаже древъ приимеши: ",
    tier: "Степень",
    sham_title: "Волхвское древнее заклятие",
    palm_title: "Возвысити пальму",
    sun_title: "Возвысити солнце",
    energy_title: "Укрепити силу",
    boots_title: "Крилатии сапози"
  },

  pl: {
    sell_title: "Sprzedaj swoje drewno tutaj!",
    sell_btn: "Sprzedaj",
    money: "Pieniądze",
    logs: "Drewno",
    energy: "Energia",
    settings: "Ustawienia",
    appearance_title: "Wygląd",
    appearance_mode_title: "Tryb",
    appearance_mode_dark: "Opalona Palma",
    appearance_mode_light: "Jasna Palma",
    appearance_font_title: "Czcionka",
    languages_title: "Języki",
    likely: "Po sprzedaży drewna otrzymasz: ",
    tier: "Poziom",
    sham_title: "Starożytne Zaklęcie Szamana",
    palm_title: "Ulepsz Palmę",
    sun_title: "Ulepsz Słońce",
    energy_title: "Popraw Wytrzymałość",
    boots_title: "Skrzydlate Buty"
  },

  ka: {
  sell_title: "აქ გაყიდე შენი მორები!",
  sell_btn: "გაყიდვა",
  money: "ფული",
  logs: "მორები",
  energy: "ენერგია",
  settings: "პარამეტრები",
  appearance_title: "გარეგნობა",
  appearance_mode_title: "რეჟიმი",
  appearance_mode_dark: "მზით დამწვარი პალმა",
  appearance_mode_light: "ნათელი პალმა",
  appearance_font_title: "შრიფტი",
  languages_title: "ენები",
  likely: "გაყიდვის შემდეგ მიიღებ: ",
  tier: "დონე",
  sham_title: "უძველესი შამანის შელოცვა",
  palm_title: "პალმის გაუმჯობესება",
  sun_title: "მზის გაუმჯობესება",
  energy_title: "გამძლეობის გაუმჯობესება",
  boots_title: "ფრთიანი ჩექმები"
},

uk: {
  sell_title: "Продай свої колоди тут!",
  sell_btn: "Продати",
  money: "Гроші",
  logs: "Колоди",
  energy: "Енергія",
  settings: "Налаштування",
  appearance_title: "Зовнішній вигляд",
  appearance_mode_title: "Режим",
  appearance_mode_dark: "Засмагла пальма",
  appearance_mode_light: "Світла пальма",
  appearance_font_title: "Шрифт",
  languages_title: "Мови",
  likely: "Після продажу ти отримаєш: ",
  tier: "Рівень",
  sham_title: "Давнє шаманське закляття",
  palm_title: "Покращити пальму",
  sun_title: "Покращити сонце",
  energy_title: "Покращити витривалість",
  boots_title: "Крилаті чоботи"
},

  sr: {
    sell_title: "Продај своја дрва овде!",
    sell_btn: "Продај",
    money: "Новац",
    logs: "Дрва",
    energy: "Енергија",
    settings: "Подешавања",
    appearance_title: "Изглед",
    appearance_mode_title: "Режим",
    appearance_mode_dark: "Опалјена палма",
    appearance_mode_light: "Светла палма",
    appearance_font_title: "Фонт",
    languages_title: "Језици",
    likely: "Након продаје дрва добићеш: ",
    tier: "Ниво",
    sham_title: "Древна шаманска чаролија",
    palm_title: "Унапреди палму",
    sun_title: "Унапреди сунце",
    energy_title: "Побољшај издржљивост",
    boots_title: "Крилате чизме"
  },

  fr: {
    sell_title: "Vendez vos bûches ici !",
    sell_btn: "Vendre",
    money: "Argent",
    logs: "Bûches",
    energy: "Énergie",
    settings: "Paramètres",
    appearance_title: "Apparence",
    appearance_mode_title: "Mode",
    appearance_mode_dark: "Palmier Bronzé",
    appearance_mode_light: "Palmier Clair",
    appearance_font_title: "Police",
    languages_title: "Langues",
    likely: "Après la vente, vous recevrez : ",
    tier: "Niveau",
    sham_title: "Sort ancien du chaman",
    palm_title: "Améliorer le palmier",
    sun_title: "Améliorer le soleil",
    energy_title: "Améliorer l'endurance",
    boots_title: "Bottes ailées"
  },

  cu: {
    sell_title: "Продай древеса зде!",
    sell_btn: "Продати",
    money: "Сребро",
    logs: "Древеса",
    energy: "Сила",
    settings: "Устав",
    appearance_title: "Вид",
    appearance_mode_title: "Образ",
    appearance_mode_dark: "Пальма зноя",
    appearance_mode_light: "Пальма светла",
    appearance_font_title: "Писание",
    languages_title: "Языцы",
    likely: "По продаже древъ приимеши: ",
    tier: "Степень",
    sham_title: "Древнее волхвование",
    palm_title: "Возвысити пальму",
    sun_title: "Возвысити солнце",
    energy_title: "Укрепити силу",
    boots_title: "Крилатии сапоги"
  },

  el: {
    sell_title: "Πούλησε τα ξύλα σου εδώ!",
    sell_btn: "Πώληση",
    money: "Χρήματα",
    logs: "Ξύλα",
    energy: "Ενέργεια",
    settings: "Ρυθμίσεις",
    appearance_title: "Εμφάνιση",
    appearance_mode_title: "Λειτουργία",
    appearance_mode_dark: "Ηλιοκαμένη Φοινικιά",
    appearance_mode_light: "Φωτεινή Φοινικιά",
    appearance_font_title: "Γραμματοσειρά",
    languages_title: "Γλώσσες",
    likely: "Μετά την πώληση θα λάβεις: ",
    tier: "Βαθμίδα",
    sham_title: "Αρχαίο Ξόρκι Σαμάνου",
    palm_title: "Αναβάθμιση Φοινικιάς",
    sun_title: "Αναβάθμιση Ήλιου",
    energy_title: "Βελτίωση Αντοχής",
    boots_title: "Φτερωτές Μπότες"
  },

  ar: {
    sell_title: "بع أخشابك هنا!",
    sell_btn: "بيع",
    money: "المال",
    logs: "الأخشاب",
    energy: "الطاقة",
    settings: "الإعدادات",
    appearance_title: "المظهر",
    appearance_mode_title: "الوضع",
    appearance_mode_dark: "نخلة محترقة بالشمس",
    appearance_mode_light: "نخلة مضيئة",
    appearance_font_title: "الخط",
    languages_title: "اللغات",
    likely: "بعد البيع ستحصل على: ",
    tier: "المستوى",
    sham_title: "تعويذة الشامان القديمة",
    palm_title: "تطوير النخلة",
    sun_title: "تطوير الشمس",
    energy_title: "تحسين التحمل",
    boots_title: "أحذية مجنحة"
  },

  de: {
    sell_title: "Verkaufe deine Holzstämme hier!",
    sell_btn: "Verkaufen",
    money: "Geld",
    logs: "Holz",
    energy: "Energie",
    settings: "Einstellungen",
    appearance_title: "Aussehen",
    appearance_mode_title: "Modus",
    appearance_mode_dark: "Sonnengebrannte Palme",
    appearance_mode_light: "Helle Palme",
    appearance_font_title: "Schriftart",
    languages_title: "Sprachen",
    likely: "Nach dem Verkauf erhältst du: ",
    tier: "Stufe",
    sham_title: "Uralter Schamanenzauber",
    palm_title: "Palme verbessern",
    sun_title: "Sonne verbessern",
    energy_title: "Ausdauer verbessern",
    boots_title: "Geflügelte Stiefel"
  },

  tr: {
  sell_title: "Kütüklerini burada sat!",
  sell_btn: "Sat",
  money: "Para",
  logs: "Kütükler",
  energy: "Enerji",
  settings: "Ayarlar",
  appearance_title: "Görünüm",
  appearance_mode_title: "Mod",
  appearance_mode_dark: "Güneşte Yanmış Palmiye",
  appearance_mode_light: "Açık Renkli Palmiye",
  appearance_font_title: "Yazı Tipi",
  languages_title: "Diller",
  likely: "Satıştan sonra kazanacağın: ",
  tier: "Seviye",
  sham_title: "Kadim Şaman Büyüsü",
  palm_title: "Palmiyeyi Geliştir",
  sun_title: "Güneşi Geliştir",
  energy_title: "Dayanıklılığı Artır",
  boots_title: "Kanatlı Çizmeler"
},


  zh: {
    sell_title: "在这里出售你的木材！",
    sell_btn: "出售",
    money: "金钱",
    logs: "木材",
    energy: "能量",
    settings: "设置",
    appearance_title: "外观",
    appearance_mode_title: "模式",
    appearance_mode_dark: "晒黑的棕榈",
    appearance_mode_light: "明亮的棕榈",
    appearance_font_title: "字体",
    languages_title: "语言",
    likely: "出售后你将获得：",
    tier: "等级",
    sham_title: "远古萨满法术",
    palm_title: "升级棕榈",
    sun_title: "升级太阳",
    energy_title: "提升耐力",
    boots_title: "翼靴"
  },

  fi: {
    sell_title: "Myy puusi täällä!",
    sell_btn: "Myy",
    money: "Raha",
    logs: "Puut",
    energy: "Energia",
    settings: "Asetukset",
    appearance_title: "Ulkoasu",
    appearance_mode_title: "Tila",
    appearance_mode_dark: "Auringon Polttama Palmu",
    appearance_mode_light: "Vaalea Palmu",
    appearance_font_title: "Fontti",
    languages_title: "Kielet",
    likely: "Myynnin jälkeen saat: ",
    tier: "Taso",
    sham_title: "Muinaisen Shamaanin Loitsu",
    palm_title: "Päivitä Palmu",
    sun_title: "Päivitä Aurinko",
    energy_title: "Paranna Kestävyyttä",
    boots_title: "Siivekkäät Saappaat"
  },


  ja: {
    sell_title: "ここで木材を売ろう！",
    sell_btn: "売る",
    money: "お金",
    logs: "木材",
    energy: "エネルギー",
    settings: "設定",
    appearance_title: "外観",
    appearance_mode_title: "モード",
    appearance_mode_dark: "日焼けしたヤシ",
    appearance_mode_light: "明るいヤシ",
    appearance_font_title: "フォント",
    languages_title: "言語",
    likely: "売却後に得られるもの：",
    tier: "ランク",
    sham_title: "古代シャーマンの呪文",
    palm_title: "ヤシを強化",
    sun_title: "太陽を強化",
    energy_title: "スタミナ向上",
    boots_title: "翼のブーツ"
  },

  af: {
  sell_title: "Verkoop jou hout hier!",
  sell_btn: "Verkoop",
  money: "Geld",
  logs: "Hout",
  energy: "Energie",
  settings: "Instellings",
  appearance_title: "Voorkoms",
  appearance_mode_title: "Modus",
  appearance_mode_dark: "Sonverbrande Palm",
  appearance_mode_light: "Ligte Palm",
  appearance_font_title: "Lettertipe",
  languages_title: "Tale",
  likely: "Na die verkoop kry jy: ",
  tier: "Vlak",
  sham_title: "Antieke Sjamaan-spreuk",
  palm_title: "Verbeter Palm",
  sun_title: "Verbeter Son",
  energy_title: "Verbeter Uithouvermoë",
  boots_title: "Gevlerkte Stewels"
},


  am: {
    sell_title: "እንጨቶችህን እዚህ ሽጥ!",
    sell_btn: "ሽጥ",
    money: "ገንዘብ",
    logs: "እንጨት",
    energy: "ኃይል",
    settings: "ቅንብሮች",
    appearance_title: "መልክ",
    appearance_mode_title: "ሁኔታ",
    appearance_mode_dark: "በፀሐይ የተቃጠለ ዘንባባ",
    appearance_mode_light: "ብሩህ ዘንባባ",
    appearance_font_title: "ፊደል",
    languages_title: "ቋንቋዎች",
    likely: "ከሽያጭ በኋላ ትቀበላለህ: ",
    tier: "ደረጃ",
    sham_title: "ጥንታዊ የሻማን ስልት",
    palm_title: "ዘንባባ ማሻሻል",
    sun_title: "ፀሐይ ማሻሻል",
    energy_title: "ኃይል ማሻሻል",
    boots_title: "ክንፍ ያላቸው ጫማዎች"
  },


  mew: {
    sell_title: "Meow mew",
    sell_btn: "Mrr!",
    money: "Meows",
    logs: "Mrr-Meow",
    energy: "Mrr-Meow",
    settings: "Marr..",
    appearance_title: "Mew",
    appearance_mode_title: "Mrr",
    appearance_mode_dark: "Mrr-Meow",
    appearance_mode_light: "Meow-Mrr",
    appearance_font_title: "Mew",
    languages_title: "Meow",
    likely: "Meow Meow Mrr Meow Mew: ",
    tier: "Mi",
    sham_title: "Mewew Meowen",
    palm_title: "Mewew Mrr-Mrr",
    sun_title: "Mewew Ma",
    energy_title: "Mewew mrr-meow",
    boots_title: "Mrr-Meow Boots"
  }
};